environment:
  matrix:
    - nodejs_version: 13
    - nodejs_version: 12
    - nodejs_version: 10
    - nodejs_version: 8

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - npm run alpha

build: off
